### ISSUE TITLE
Lizenzen ausweisen

### ISSUE THREAD

**Issue by tordans** [berlin/parkplatzdaten#3]
Ich fände es gut, wenn auf der Projektvorstellung die Lizenzen für Daten und ggf. Code oder Apps ausgewiesen werden. Aktuell wird nur von "offenen Daten" gesprochen, was suggeriert, die Daten wären auch in allen Fällen frei zu nutzen. Die Lizenzen zu nennen macht explizit, wie die Daten genutzt werden dürfen.

**Comment by tordans** [comment]
Die Lizenz für die Daten von https://parkraum.osm-verkehrswende.org/ ist ODbL 1.0 https://wiki.osmfoundation.org/wiki/Licence. Mit entsprechender Attribution sind die Daten daher sehr offen nutzbar.

Die verschiedenen Softwareprojekte von https://parkraum.osm-verkehrswende.org/github haben jew. ein Lizenz-File in Github.

**Comment by hanshack** [comment]
Super Idee. Habe ich für viele der Datensätze hinzugefügt.
