### ISSUE TITLE
Daten Xhain

### ISSUE THREAD

**Issue by tordans** [berlin/parkplatzdaten#4]
Xhain hat in seinem eigene Masterportal https://www.geodaten-fk.de/MeinXhain/Portal/ Daten zu Parkraum aus Parkraumstudien und anderen Quellen veröffentlicht.

<img width="367" alt="image" src="https://user-images.githubusercontent.com/111561/218511253-47986619-ff71-4f58-b70e-a2f42d098445.png">

Angaben zu Lizenz und Details zu den Daten wie Datenherkunft konnte ich online spontan nicht finden.

**Comment by hanshack** [comment]
Danke, ist schon drin. Habe den Link etwas umbennant
